# Generated by Django 2.1.2 on 2022-08-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0050_newagents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newagents',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='newagents',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='newagents',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='newagents',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='NewAgents',
        ),
    ]
