# Generated by Django 2.1.2 on 2022-12-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Airline', models.CharField(max_length=50)),
                ('Airline_IATA_Code', models.CharField(max_length=10)),
                ('IATA_Numeric_Code', models.IntegerField()),
                ('Agreement_Type', models.CharField(max_length=50)),
                ('Contraced_With', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=30)),
                ('ORC_Rate', models.FloatField()),
                ('Gross', models.FloatField()),
                ('Nett', models.FloatField()),
                ('ORC_Actual', models.FloatField()),
            ],
        ),
    ]
