# Generated by Django 2.1.2 on 2022-12-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Agreement_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Airline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Airline_IATA_Code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Contraced_With',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Month',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Nett',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='ORC_Actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='ORC_Rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
