# Generated by Django 2.1.2 on 2022-12-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20221221_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Agreement_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Airline_IATA_Code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Contraced_With',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
