# Generated by Django 2.1.2 on 2022-12-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20221221_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Agreement_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
