# Generated by Django 2.1.2 on 2022-12-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20221221_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='Contraced_With',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
