# Generated by Django 2.1.2 on 2022-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200928_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionhistory',
            name='add_yq_yr',
            field=models.BooleanField(default=False),
        ),
    ]
