# Generated by Django 2.1.2 on 2022-04-17 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_commissionhistory_add_yq_yr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0024_auto_20190405_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('agency_no', models.CharField(blank=True, max_length=99, null=True)),
                ('trade_name', models.CharField(max_length=199, null=True)),
                ('address1', models.CharField(blank=True, max_length=99, null=True)),
                ('address2', models.CharField(blank=True, max_length=99, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('home_agency', models.CharField(blank=True, max_length=99, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Defaulted'), ('R', 'Revoked'), ('S', 'Reinstated'), ('T', 'Terminated')], default='A', max_length=1, null=True)),
                ('from_old_asplinks', models.BooleanField(default=False)),
                ('agency_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_agencies2', to='agency.AgencyCollection')),
                ('agency_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies2', to='agency.AgencyType')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies2', to='main.Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency2_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency2_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('sales_owner', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agencies2', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.State')),
            ],
            options={
                'permissions': (('download_agencylist', 'Can download agency list'),),
                'ordering': ['-trade_name'],
            },
            managers=[
                ('csv', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='from_old_asplinks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='agency2',
            unique_together={('agency_no', 'country')},
        ),
    ]
